sudo: required
services:
  - docker

before_install:
  - docker build -t craigsmith/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run craigsmith/react-test npm test -- --coverage

after_success:
  - docker build -t craigsmith132/multi-client ./client
  - docker build -t craigsmith132/multi-nginx ./nginx
  - docker build -t craigsmith132/multi-server ./server
  - docker build -t craigsmith132/multi-worker ./worker

#log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push images to dockerhub
  - docker push craigsmith132/multi-client
  - docker push craigsmith132/multi-nginx
  - docker push craigsmith132/multi-server
  - docker push craigsmith132/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-737017274809
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY